steps:
- id: build-docker-images
  name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-west2-docker.pkg.dev/dockerk8sstudy/lotto/lotto:latest .
  automapSubstitutions: true

- id: deploy-cloud-run
  name: 'gcr.io/cloud-builders/gcloud'
  script: |
    gcloud run deploy lotto --image us-west2-docker.pkg.dev/dockerk8sstudy/lotto/lotto:latest --region us-west2 --platform managed --allow-unauthenticated
  
images:
- 'us-west2-docker.pkg.dev/dockerk8sstudy/lotto/lotto:latest'
