# Reference: https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run?hl=ko
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west2-docker.pkg.dev/dockerk8sstudy/lotto/lotto:latest', '.']
  
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west2-docker.pkg.dev/dockerk8sstudy/lotto/lotto:latest']
  
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'lotto', '--image', 'us-west2-docker.pkg.dev/dockerk8sstudy/lotto/lotto:latest', '--region', 'us-west2']
  
images:
- 'us-west2-docker.pkg.dev/dockerk8sstudy/lotto/lotto:latest'
